# Generated by Django 4.2.6 on 2023-10-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='изображение')),
                ('tip', models.CharField(max_length=200, verbose_name='категория')),
                ('purchase_price', models.IntegerField(blank=True, null=True, verbose_name='цена за покупку')),
                ('date_of_creation', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('date_of_last_modification', models.DateField(blank=True, null=True, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
