# Generated by Django 4.2.6 on 2023-10-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=200, verbose_name='наименование категории')),
                ('description_category', models.TextField(blank=True, null=True, verbose_name='описание категории')),
            ],
        ),
    ]
