# Generated by Django 4.2.6 on 2023-10-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description_category',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tip',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1705, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория'),
            preserve_default=False,
        ),
    ]
